### ISSUE TITLE
See, please reply.

### ISSUE THREAD

**Issue by pengzhengfa** [authorjapps/performance-tests#4]
Hello, your case is really not clear, can help write an interface test case no, to tell the truth, you write this is not very detailed, how to generate reports and so on, write is not very clear.

**Comment by authorjapps** [comment]
Hello,

I am trying to understand your requirement.

Can you please join our Slack channel and Mailing list please ?

We can discuss there and all  other collaborators can respond to solve the
issues quickly.

*Slack* Channel link:
https://join.slack.com/t/zerocode-workspace/shared_invite/enQtNzIyNDUwOTg2NDUzLWQ3ZTM1YTBhNjJmNzY3NmU0Y2I4NWIwZDVjYjk4M2JhYWY5NzA3ZWEwMWIwOTIwOWFjNTg2YzFmNzZhYTUyYzI

*Mailing* list Link:
https://groups.google.com/forum/#!forum/zerocode-automation

The below Wiki page might help you.
Link: https://github.com/authorjapps/performance-tests

**Comment by authorjapps** [comment]
Linked Issue - https://github.com/authorjapps/zerocode/issues/292
